import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/header";
import Footer from "./_components/Footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
